services: # Different containers to compose
  nginx:
    image: nginx:alpine # docker hub image
    container_name: nginx # container name so its not random
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # mount the nginx.conf in terminal into the containers default.conf (which is what the container would use internally for nginx)
                                                    # Editing nginx.conf locally would change what the container uses.
    ports:
      - "80:80" # punches a hole between ec2 instance and container at port 80. http request -> ec2:80 /hole/ -> container:nginx -> ...
    networks:
      - my-network # communication from container <-> container. Every service on my-network can communicate with eachother internally.
    depends_on: # create container after flask container.
      - flask

  db:
    image: mariadb:11
    environment: # Below are somehow variables that areused to init database
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: reconciliation_db
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    networks: # Add this db service to the internal shared docker network for this compose ecosystem
      - my-network
    volumes:
      - db_data:/var/lib/mysql # Docker creates and manages a storage volume: "db_data" in /var/lib/docker/volumes/
                               # and mounts it to a folder: "/var/lib/mysql" inside the container
                               # so everything written in /var/lib/mysql in container is also written to db_data on EC2 vm.
      - ./src/models/schema.sql:/docker-entrypoint-initdb.d/init.sql # /docker-entrypoint-initdb.d/ is a convention built into mysql:8 image. On first startup, run all .sql files in that folder (DDL, DML).
                                                                     # therefore take the init.sql file in the terminal and mount it to /docker-entrypoint-initdb.d/init.sql

  flask:
    build: # build an image from scratch instead of using pre buitl image
      context: .
      dockerfile: docker/Dockerfile
    container_name: flask
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: reconciliation_db
      PYTHONUNBUFFERED: "1"

    # Run 4 workers of the Flask app in app.py, listen for connections on :5000 (nginx will forward to that port from :80)
    command: gunicorn app:app --bind 0.0.0.0:5000 --workers 4 --access-logfile - --error-logfile - --capture-output --log-level debug
    # docker compose logs -f flask                       

    networks: # join this container on the my-network and alias it
      - my-network

    depends_on:
      - db

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    expose:
      - "9090"
    networks:
      - my-network
    depends_on:
      - flask

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    expose:
      - "3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"

      # defines the public url that users will use to access grafana
      # %(protocol)s becomes http dynamically
      # %(domain)s becomes either ip or domain name (like google.com)
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"

      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - my-network
    depends_on:
      - prometheus

volumes:
  db_data:

networks:
  my-network:
