upstream flask-app {

        server flask:5000;

} # when flask-app is called, contact the container named flask listening on port 5000 (nginx has access to flask container through my-network in docker compose)

server { # This defines how nginx should behave when receiving web requests

        listen 80; # nginx accepts http traffic on port 80, requests to http://your-ip arrive to port:80
        server_name _;
        location / {
                proxy_pass http://flask-app; # reverse proxy step, forward request to the upstream flask-app group
                proxy_set_header Host "localhost";
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_redirect off;
        }

}
