map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

upstream flask {

        server flask:5000;

} # when flask-app is called, contact the container named flask listening on port 5000 (nginx has access to flask container through my-network in docker compose)

upstream grafana {

        server grafana:3000;
}

server { # This defines how nginx should behave when receiving web requests

        listen 80; # nginx accepts http traffic on port 80, requests to http://your-ip arrive to port:80
        server_name _;
        location / {
                proxy_pass http://flask; # reverse proxy step, forward request to the upstream flask-app group
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_redirect off;
        }
        # https://grafana.com/tutorials/run-grafana-behind-a-proxy/
        location /grafana/ {
                proxy_http_version 1.1; # websockets require http 1.1, nginx originally uses 1.0
                
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                proxy_pass http://grafana/;
        }
        location /grafana {
                return 301 /grafana/;
        }

}
